Didah Morse Code PDA/Appliance: actions.h File Reference
actions.h File Reference
Application-specific actions.
#include "Arduino.h"
#include "libmorse.h"
#include "morse_token.h"
Typedefs
Predicates
typedef int(* IntPredicate) (int)
Functions
const char * getVersion ()
char getAlarmState ()
Get the low-voltage alarm state. This determines the message format and repetition interval. Returns 'V' for low, '^' for high, and '-' for nominal.
void setAlarmState (char state)
Set the low-voltage alarm state. This determines the message format and repetition interval.
uint32_t getVoltagePollInterval ()
A sample ADC reading is taken each time through the main loop, and written to a ring buffer. The samples are only filtered and converted to a voltage once every poll interval.
uint32_t getIntervalForState ()
Get the announcement interval for the current alarm state.
const char * getFormatForState ()
Get the alarm format for the current alarm state.
void txRaw (MorseToken)
Get the raw analog input.
Operations
void txSymbolStackTop (MorseToken)
Transmit the top element of the stack.
void txListSymbolStack (MorseToken)
List the contents of the symbol stack.
void txTimeHHMM (MorseToken code)
Transmit the 24-hr time.
void txTimeVerbose (MorseToken code)
void txUptime (MorseToken)
Transmit the uptime.
void txInternalTemperatureC (MorseToken code)
Transmit the internal temperature as an integer in Celsius.
void txInternalTemperatureF (MorseToken code)
Transmit the internal temperature in integer in Fahrenheit.
void txMacAddress (MorseToken code)
Transmit the mac address.
void slowDown ()
Increase the unit time by 5000 microseconds.
void speedUp ()
Decrease the unit time by 5000 microseconds.
void txAR (MorseToken)
Transmit the AR prosign three times.
void txEcho (MorseToken code)
Transmit II <code> AR.
void txGreeting (MorseToken code)
Transmit CQ CQ CQ DE ET1 ET1 K.
void getPressure (MorseToken code)
void printLog ()
Report the current settings and sensor values via the serial port.
void printBanner ()
Print documentation for the commands via the serial port.
void setVolume (MorseToken)
Attempt to control the output volume but adjusting the PWM duty cycle.
void txHelp (MorseToken)
Transmit help text.
void txMenu (MorseToken)
Transmit a tersely-worded command list.
void txSettings (MorseToken)
Transmit the current settings and sensor values.
Aural Feedback
void txTick (MorseToken code)
void txTiTick (MorseToken code)
Play a brief pair high-pitched chirps.
void txTock (MorseToken code)
Morse Code Input
bool readRange (uint32_t &result, const char *prompt, uint32_t minimum, uint32_t maximum)
Prompt for a value from the serial port.
void readEdit (char *buffer, bool &isNotTooLate, const char *end, IntPredicate isIncluded, uint32_t timeout)
Read a line from the serial port with support for rubbing out preceding characters.
bool readLine (char *buffer, size_t n, uint32_t timeout=60000000)
Read a string from the serial terminal up to a return or the end of the buffer. Return false if timeout milliseconds elapse before either a return is sent or the buffer is filled including null termination. In all cases the buffer is null-terminated.
bool readNumber (uint32_t &v, uint32_t timeout=60000000)
Action Mapping and Dispatching
typedef void(* ActionFn) (MorseToken)
void initActions ()
Initialize the table of function pointers to no-ops.
uint8_t codeHash (MorseToken code)
void assignAction (MorseToken code, ActionFn action)
Hash a Morse code symbol to a table location and store action there.
void doAction (MorseToken code)
Invoke an action from the actions table.
void saveActions ()
void restoreActions ()
void push1RestoreAll (MorseToken code)
uint8_t matchScore (const char *pattern)
Score the given pattern against the state of the symbol stack.
void dispatchOnStack (MorseToken)
void mapToUpper (char *buffer, size_t n)
Perform in-place conversion of the given buffer to upper case.
bool isValidMorseFormat (const char *buffer, size_t n)
Check for unsupported punctuation and some invalid escape sequences.
void readEvalPrint ()
Respond to commands from the serial port.
Detailed Description
Application-specific actions.
Definition in file actions.h.
Function Documentation
uint8_t codeHash (MorseToken code)
Our internal representation of Morse code is left justified, that is to say, the high order bit is the first dit/dah. Most of the time, the bottom 8 bits will be zero, so create a hash by grabbing the top 8 bits.
Actually, the comment above applies when MorseToken is defined to be larger than 8 bits. Currently sizeof(MorseToken) == 1, so codeHash(x) == x.
Definition at line 35 of file actions.cpp.
Referenced by assignAction(), and doAction().
{
   return code >> (wordBits - CHAR_BIT);
 }
void dispatchOnStack (MorseToken)
Execute the command that best matches the stack contents.
Note
The caller graph is incorrect. A pointer to this function is passed in setup() but the caller is doAction().
Definition at line 76 of file actions.cpp.
References clearSymbolStack(), exchangeStack(), getLowVoltageThresholdDefault(), getMaximumVoltage(), initSettings(), matchScore(), popN(), printLog(), pushSymbolStack(), rxString(), setAlarmHighFormat(), setAlarmInterval(), setAlarmLowFormat(), setAnnouncementFormat(), setAnnouncementInterval(), setDitMicros(), setHighVoltageThreshold(), setLowVoltageThreshold(), setTxHz(), slowDown(), speedUp(), stackDigitsToUnsigned(), txError(), txHelp(), txListSymbolStack(), txString(), txSymbolStackTop(), and txTimeHHMM().
Referenced by setup().
{
    pushSymbolStack(code);
    if (matchScore("V") == 255) {
       // Pop the 'V'.
       popN(1);
       // Transmit the top of the stack.
       txSymbolStackTop(MorseToken());
    } else if (matchScore("QRS") == 255) {
       // Increase the dit time.
       slowDown();
       popN(3);
    } else if (matchScore("QRQ") == 255) {
       // Decrease the dit time.
       speedUp();
       popN(3);
    } else if (matchScore("QTR?") == 255) {
       // Ask the time.
       txTimeHHMM(MorseToken());
       popN(4);
    } else if (matchScore("C") == 255) {
       // Clear the stack.
       clearSymbolStack(MorseToken());
       Serial.println("Cleared stack.");
    } else if (matchScore("nA") == 255) {
       // Set the low voltage threshold.
       popN(1);
       uint32_t n(stackDigitsToUnsigned());
       const uint32_t hi(getMaximumVoltage() - getLowVoltageThresholdDefault());
       if (n - getLowVoltageThresholdDefault() < hi) {
          setLowVoltageThreshold(n);
          txString("K");
       } else {
          txError();
          txString("RANGE");
       }
    } else if (matchScore("nB") == 255) {
       // Set the high voltage threshold.
       popN(1);
       uint32_t n(stackDigitsToUnsigned());
       const uint32_t hi(getMaximumVoltage() - getLowVoltageThresholdDefault());
       if (n - getLowVoltageThresholdDefault() < hi) {
          setHighVoltageThreshold(n);
          txString("K");
       } else {
          txError();
          txString("RANGE");
       }
    } else if (matchScore("nD") == 255) {
       // Set the dit duration.
       popN(1);
       uint32_t n(stackDigitsToUnsigned());
       if (n - 20 <= 200 - 20) {
          setDitMicros(1000 * n);
          txString("K");
       } else {
          txError();
          txString("RANGE");
       }
    } else if (matchScore("F") == 255) {
       // Get the announcement format.
       popN(1);
       txString("TX MSG END WITH ^AR^  K");
       char buffer[128];
       rxString(buffer, sizeof buffer);
       if (buffer[0]) {
          txString("K");
          setAnnouncementFormat(buffer);
       } else {
          txString("QTA");
       }
    } else if (matchScore("G") == 255) {
       // Copy the alarm format.
       popN(1);
       txString("TX MSG END WITH ^AR^  K");
       char buffer[128];
       rxString(buffer, sizeof buffer);
       if (buffer[0]) {
          txString("K");
          setAlarmLowFormat(buffer);
       } else {
          txString("QTA");
       }
    } else if (matchScore("H") == 255) {
       // Copy the alarm format.
       popN(1);
       txString("TX MSG END WITH ^AR^  K");
       char buffer[128];
       rxString(buffer, sizeof buffer);
       if (buffer[0]) {
          txString("K");
          setAlarmHighFormat(buffer);
       } else {
          txString("QTA");
       }
    } else if (matchScore("c^SS^") == 255) {
       // Erase the top of the stack.
       popN(2);
       txListSymbolStack(MorseToken());
       txString("K");
    } else if (matchScore("nI") == 255) {
       // Set the nominal announcement repetition interval.
       popN(1);
       uint32_t n(stackDigitsToUnsigned());
       if (n - 20 < 86400 - 20) {
          setAnnouncementInterval(n);
          txString("K");
       } else {
          txError();
          txString("RANGE");
       }
    } else if (matchScore("nJ") == 255) {
       // Set the alarm announcement repetition interval.
       popN(1);
       uint32_t n(stackDigitsToUnsigned());
       if (n - 20 <= 86400 - 20) {
          setAlarmInterval(n);
          txString("K");
       } else {
          txError();
          txString("RANGE");
       }
    } else if (matchScore("nQTR") == 255 || matchScore("nT") == 255) {
       // Set the time without the four-digit requirement.
       popN(1);
       uint32_t n(stackDigitsToUnsigned());
       uint32_t hour(n / 100);
       uint32_t minute(n % 100);
       if (hour < 24 && minute < 60) {
          setTime(hour, minute, 0, 0, 0, 0);
          setUptime(0);
          txString("K");
       } else {
          txError();
          txString("RANGE");
       }
    } else if (matchScore("O") == 255) {
       initSettings();
       Serial.println("Settings restored.\r\n");
       printLog();
       txString("K");
    } else if (matchScore("nP") == 255) {
       // Set the pitch of the side tone.
       popN(1);
       uint32_t n(stackDigitsToUnsigned());
       if (n - 55 <= 1760 - 55) {
          setTxHz(n);
          txString("K");
       } else {
          txError();
          txString("RANGE");
       }
    } else if (matchScore("X") == 255) {
       // Exchange the top two elements of the stack.
       popN(1);
       exchangeStack(MorseToken());
       txListSymbolStack(MorseToken());
       txString("K");
    } else if (matchScore("?") == 255) {
       // Transmit the help text.
       popN(1);
       txHelp(MorseToken());
    }
 }
void getPressure (MorseToken code)
Play a tone with pitch proportional to the pressure on the dit button.
Definition at line 355 of file actions.cpp.
References dahPin, ditPin, getDitMicrosDefault(), pwmFrequency(), pwmWrite(), touchPoll(), and txString().
{
   txString("");
   pwmFrequency(0);
   pwmWrite(getDuty());
   while (!touchPoll(dahPin)) {
     uint32_t ci(touchRead(ditPin));
     Serial.println(ci);
     uint32_t f(map(ci, 500, 65535, 33, 4186));
     pwmFrequency(f);
     pwmWrite(getDuty());
     delayMicroseconds(getDitMicrosDefault());
   }
   txString("^AR^");
 }
void initActions ()
Initialize the table of function pointers to no-ops.
The actions table is indexed by the bottom 8 bits of our internal representation of a Morse code character or prosign. Actions are passed MorseToken instances so that a single action can handle several different tokens.
For more complicated command syntax, dispatchOnStack() in actions.cpp performs pattern matching on the stack and dispatches to the first command that matches.
The intent was to support command rebinding at runtime while being efficient enough to run on a low-powered processor.
Definition at line 29 of file actions.cpp.
Referenced by setup().
                    {
   for (size_t i(0); i < actionSize; ++i) {
     actions[i] = doNothing;
   }
 }
bool isValidMorseFormat (const char * buffer, size_t n)
Check for unsupported punctuation and some invalid escape sequences.
Substitution placeholders C, F, T, U, and V are checked; prosign escape sequences are not.
Definition at line 676 of file actions.cpp.
Referenced by readMessageFormat().
{
   bool result(true);
   for (size_t i(0); i < n; ++i) {
     const char c(buffer[i]);
     if (ispunct(c)) {
       if (strchr(morsePunctuation, c)) {
     ; // ok
       } else if (c == '%' && i + 1 < n && strchr("CFTUV", buffer[i + 1])) {
     ; // ok
       } else if (c == '^') {
     ; // ok, not checking prosign overflow, matched delimiters, or
       // embedded escape sequences, e.g.
       //    ^^
           //    ^%F^
       } else {
     result = false;
     break;
       }
     } else if (!c) {
       break;
     }
   }
   return result;
 }
uint8_t matchScore (const char * pattern)
Score the given pattern against the state of the symbol stack.
The maximum score is 255 and decreases with increased distance from the pattern.
A-Z, 0-9, punctuation - Match a literal character
^CQ^ - Match a prosign
space - Match a word-length or greater pause
a - Match a single letter from A-Z
c - Match any character
d - Match a single digit
n - Match a contiguous sequence of digits
With the exception of n, all the pattern elements match one Morse token. The following punctuation is accepted:
!"$&'()+,-./:;=?@_
The pattern is compared to the stack starting at the end of the pattern and the top of the stack. There is no support for backtracking. All pattern elements are greedy.
Definition at line 265 of file libmorse.cpp.
References getDitMicros(), getMorse(), MORSE_AR, MORSE_BT, s(), symbolStackSize(), txString(), and txTock().
Referenced by dispatchOnStack().
{
    uint8_t score(255);
    const char* patEnd(pattern);
    while (*patEnd) ++patEnd;
    const char* patSym(patEnd);
    if (patSym == pattern) {
       score = 0;
       // Null pattern never matches.
       return score;
    }
    --patSym;
    size_t sp(0);
    bool sawDigit(false);
    do {
       char si(s(sp).toChar());
       switch (*patSym) {
       case 'a':
          // Match any (simple greedy match).
          // Must occur at the beginning of the pattern.
          return score;
          break;
       case 'c':
          // Match a character.
          score -= score && !isalnum(si);
          break;
       case 'd':
          // Match a digit.
          score -= score && (uint8_t(9U) < uint8_t(si - '0'));
          break;
       case 'n':
          // Match one or more digits.
          // Note: only the stack size limits the number of digits.
          if (uint8_t(si - '0') < 10U) {
             sawDigit = true;
             // Don't advance to the next character of pattern.
             ++patSym;
          } else {
             if (!sawDigit) {
                score -= !!score;
             } else {
                // Finished matching n. Advance the pattern, but reuse
                // the current stack element.
                --sp;
             }
          }
          break;
       case '^': {
          // Match a prosign.
          // Note: This code is just enough different than txString to
          // be annoying.
          char pbuffer[5] = { '1', '2', '3', '4', '\0' };
          char* pb(pbuffer);
          --patSym;
          while (*patSym && (*patSym != '^')) {
             *pb++ = *patSym--;
          }
          --patSym;
          *pb-- = 0;
          // Reverse pbuffer since we're matching backwards, but the
          // prosign is a single multi-character entity.
          char* fb(pbuffer);
          while (fb < pb) {
             char temp(*fb);
             *fb++ = *pb;
             *pb-- = temp;
          }
          score -= score &&
             uint8_t(MorseToken(pbuffer, MorseToken::Prosign)) != s(sp);
          break;
       }
       default:
          // Match the literal value of c.
          score -= score && si != uint8_t(*patSym);
       };
    } while (pattern < patSym-- && ++sp != symbolStackSize());
    if (pattern != patSym && sp == symbolStackSize()) {
       // If the pattern wasn't used completely deduct a point for
       // ever unused pattern symbol.
       score -= patSym - pattern;
    }
    return score;
 }
void printLog ()
Report the current settings and sensor values via the serial port.
Report the current settings and sensor values via the serial port.
Definition at line 456 of file actions.cpp.
References getAlarmHighFormat(), getAlarmInterval(), getAlarmLowFormat(), getAlarmState(), getAnnouncementFormat(), getAnnouncementInterval(), getDitMicros(), getHighVoltageThreshold(), getInternalTemperatureC(), getLowVoltageThreshold(), getTxHz(), isTimeSet(), and readMillivolts().
Referenced by dispatchOnStack(), and readEvalPrint().
                 {
    Serial.print(
       "Didah Voltage Monitor\r\n"
       "=====================\r\n");
    printLabelValueUnits("Version: ", getVersion(), "");
    Serial.print(
       "Documentation: http://pictographer.com/didah\r\n"
       "\r\n"
       "Device to periodically announce input voltage in Morse code.\r\n"
       "\r\n");
    Serial.print(
       "Measurements\r\n"
       "--------\r\n");
    //            0         1         2
    //            012345678901234567890
    char buffer[] = "HHMM";
    unsigned int m(minute());
    unsigned int h(hour());
    buffer[0]  = '0' + h / 10;
    buffer[1]  = '0' + h % 10;
    buffer[2] = '0' + m / 10;
    buffer[3] = '0' + m % 10;
    printLabelValueUnits("Time: ", buffer,
                         isTimeSet() ? "" : " (Unset. Use T to set.)");
    // Uptime is incremented only when the time is set.
    uint32_t u(getUptime());
    // If this is still running 7,656 years from now, send me a bug report
    // about the overflow.
    printLabelValueUnits("Uptime: ", 15 * u,
                         isTimeSet() ? " minutes" : " minutes (Previous run.)");
    const char* vl[] = {
       " (INTERNAL ERROR)",
       " mV ALARM LOW!",
       " mV (Nominal)",
       " mV ALARM HIGH!"
    };
    size_t vi(0);
    switch (getAlarmState()) {
    case voltageLow:     vi = 1; break;
    case voltageNominal: vi = 2; break;
    case voltageHigh:    vi = 3; break;
    default:             vi = 0;
    }
    printLabelValueUnits("Measured voltage: ", readMillivolts(), vl[vi]);
    printLabelValueUnits("Temperature: ", getInternalTemperatureC(), " C");
    Serial.println();
    Serial.print(
       "Settings\r\n"
       "--------\r\n");
    printLabelValueUnits(
       "Nominal announcement format: ", getAnnouncementFormat(), "");
    printLabelValueUnits(
       "Nominal announcement interval: ", getAnnouncementInterval(), " seconds");
    printLabelValueUnits(
       "Low-voltage alarm threshold: ", getLowVoltageThreshold(), " mV");
    printLabelValueUnits(
       "Low-voltage alarm announcement format: ", getAlarmLowFormat(), "");
    printLabelValueUnits(
       "High-voltage alarm threshold: ", getHighVoltageThreshold(), " mV");
    printLabelValueUnits(
       "High-voltage alarm announcement format: ", getAlarmHighFormat(), "");
    printLabelValueUnits(
       "Alarm interval: ", getAlarmInterval(), " seconds");
    printLabelValueUnits("Dit duration: ", getDitMicros()/1000, " ms");
    printLabelValueUnits("Output frequency: ", getTxHz(), " Hz");
    Serial.println();
 }
void push1RestoreAll (MorseToken code)
Push the most recent symbol onto the stack, and then restore all the actions to their previous values.
Definition at line 71 of file actions.cpp.
References pushSymbolStack(), and restoreActions().
Referenced by askNext(), and askNextAlfa().
{
   pushSymbolStack(code);
   restoreActions();
 }
bool readNumber (uint32_t & v, uint32_t timeout = 60000000)
Read a non-negative integer from the Serial port. Return true if at least one digit was read before the timeout.
Definition at line 659 of file actions.cpp.
References readEdit().
Referenced by readRange().
{
   bool isNotTooLate(true);
   char buffer[32];
   const char* e(buffer + sizeof buffer - 1);
   readEdit(buffer, isNotTooLate, e, isdigit, timeout);
   v = strtoul(buffer, 0, 10);
   return isNotTooLate;
 }
bool readRange (uint32_t & result, const char * prompt, uint32_t minimum, uint32_t maximum)
Prompt for a value from the serial port.
If the value read is within the given range, assign it to the result. A true return value indicates a value within range was obtained.
Definition at line 589 of file actions.cpp.
References readNumber().
Referenced by readEvalPrint().
 {
    Serial.print(prompt);
    uint32_t v;
    bool gotOne(readNumber(v));
    bool isInRange(v - minimum <= maximum - minimum);
    if (gotOne) {
       if (isInRange) {
          result = v;
       } else {
          Serial.print("\r\nOut of range. Value must be between ");
          Serial.print(minimum);
          Serial.print(" and ");
          Serial.print(maximum);
          Serial.println(".");
       }
    } else {
       Serial.println("\r\nInvalid number. Aborting.");
    }
    return gotOne && isInRange;
 }
void restoreActions ()
If there are actions saved, restore them. Otherwise, transmit an error.
Definition at line 60 of file actions.cpp.
References restorePending(), and txError().
Referenced by getDigitByWeight(), and push1RestoreAll().
                       {
   if (restorePending) {
     for (size_t i(0); i < actionSize; ++i) {
       actions[i] = savedActions[i];
     }
     restorePending = false;
   } else {
     txError();
   }
 }
void saveActions ()
Save all the action pointers in preparation for overwriting some or all of them with action pointers for a mode. If the actions have been saved previously, the actions are not saved and the previously saved actions are not disturbed.
Definition at line 51 of file actions.cpp.
References restorePending().
Referenced by askNext(), askNextAlfa(), and askSum().
                    {
   if (!restorePending) {
     restorePending = true;
     for (size_t i(0); i < actionSize; ++i) {
       savedActions[i] = actions[i];
     }
   }
 }
void setVolume (MorseToken)
Attempt to control the output volume but adjusting the PWM duty cycle.
Note
This approach is not terribly effective. Perhaps for lack of proper output filtering.
Definition at line 579 of file actions.cpp.
References MorseToken::m2i(), popN(), s(), and symbolStackSize().
{
   size_t n(symbolStackSize());
   size_t dutyCycle(0);
   (2 < n) && (dutyCycle += 100 * s(2).m2i());
   (1 < n) && (dutyCycle +=  10 * s(1).m2i());
   (0 < n) && (dutyCycle +=   1 * s(0).m2i());
   popN(3 - (2 < n) - (1 < n));
   setDuty(dutyCycle);
 }
void txTick (MorseToken code)
Play a brief high-pitched chirp to signify the end of the waiting period for adding symbols to a token.
Definition at line 370 of file actions.cpp.
References getDitMicrosDefault(), noteHz, and playTone().
Referenced by getMorse(), and txMetronome().
{
   playTone(noteHz[96], getDitMicrosDefault()/2);
 }
void txTimeVerbose (MorseToken code)
Transmit the time verbosely. The announcement starts with QRT and repeats the time twice.
Definition at line 266 of file actions.cpp.
References txString().
{
   //               0         1         2
   //               012345678901234567890
   char buffer[] = "QRT QRT HH MM ? HH MM";
   unsigned int m(minute());
   unsigned int h(hour());
   buffer[8]  = '0' + h / 10;
   buffer[9]  = '0' + h % 10;
   buffer[11] = '0' + m / 10;
   buffer[12] = '0' + m % 10;
   buffer[16] = buffer[8];
   buffer[17] = buffer[9];
   buffer[19] = buffer[11];
   buffer[20] = buffer[12];
   txString(buffer);
 }
void txTock (MorseToken code)
Play a brief high-pitched chirp to signify the end of the waiting period for adding characters to a word.
Definition at line 380 of file actions.cpp.
References dahPin, ditPin, getDitMicrosDefault(), getPinThreshold(), noteHz, and playTone().
Referenced by matchScore(), and rxString().
{
   playTone(noteHz[84], getDitMicrosDefault()/2);
 }