Didah Morse Code PDA/Appliance: didah.ino File Reference
didah.ino File Reference
Top-level entry points for the Morse code PDA/Application.
#include <cctype>
#include "Arduino.h"
#include <EEPROM.h>
#include "EEPROMAnything.h"
#include "settings.h"
#include "actions.h"
#include "stack.h"
#include "prosign.h"
#include "Time.h"
Functions
void setup ()
void loop ()
Detailed Description
Top-level entry points for the Morse code PDA/Application.
Definition in file didah.ino.
Function Documentation
void loop ()
The main loop polls the source voltage, touch sensors, serial port input buffer, and time. It dispatches commands entered via serial port or touch sensors. It updates the status LEDs.
Definition at line 683 of file didah.ino.
References doAction(), getAlarmState(), getFormatForState(), getHighVoltageThreshold(), getIntervalForState(), getLowVoltageThreshold(), getMorse(), getRadioStartupDelay(), readEvalPrint(), readMillivolts(), redLED(), sampleVoltage(), setAlarmState(), MorseToken::toChar(), toggleGreenLED(), txEnablePin, txString(), updateUptime(), and MorseToken::valid().
             {
    sampleVoltage();
    // Gather Morse code symbols from touch input and invoke an
    // evaluation function on them.
    MorseToken token(getMorse());
    time_t currentSeconds(now());
    // Update the voltage alarm state.
    long vin(readMillivolts());
    if (vin <= getLowVoltageThreshold()) {
       setAlarmState('v');
    } else if (getHighVoltageThreshold() <= vin) {
       setAlarmState('^');
    } else {
       setAlarmState('-');
    }
    updateUptime();
    if (token.valid()) {
       Serial.println(token.toChar());
       doAction(token);
    } else if (currentSeconds % getIntervalForState() == 0) {
       digitalWrite(txEnablePin, HIGH);
       delayMicroseconds(getRadioStartupDelay());
       txString(getFormatForState());
       digitalWrite(txEnablePin, LOW);
    } else if (Serial.available()) {
       readEvalPrint();
    } else {
       toggleGreenLED();
       redLED(getAlarmState() != '-');
    }
 }
void setup ()
Arduino is basically C++ with a default main() that calls setup() once, and then calls loop() repeatedly.
Definition at line 630 of file didah.ino.
References a2m(), assignAction(), dispatchOnStack(), EEPROM_readAnything(), initActions(), initPorts(), MORSE_AR, MORSE_AS, MORSE_CT, MORSE_SS, printBanner(), pushSymbolStack(), txMenu(), txSettings(), txString(), and txUptime().
              {
    initPorts();
    initActions();
    for (size_t i(0); i < 10; ++i) {
       assignAction(a2m(i + '0'), pushSymbolStack);
    }
    assignAction(a2m('A'), dispatchOnStack);
    assignAction(a2m('B'), dispatchOnStack);
    assignAction(a2m('C'), dispatchOnStack);
    assignAction(a2m('D'), dispatchOnStack);
    assignAction(a2m('F'), dispatchOnStack);
    assignAction(a2m('G'), dispatchOnStack);
    assignAction(a2m('H'), dispatchOnStack);
    assignAction(a2m('I'), dispatchOnStack);
    assignAction(a2m('J'), dispatchOnStack);
    assignAction(a2m('K'), dispatchOnStack);
    assignAction(a2m('L'), txSettings);
    assignAction(a2m('M'), txMenu);
    assignAction(a2m('O'), dispatchOnStack);
    assignAction(a2m('P'), dispatchOnStack);
    assignAction(a2m('Q'), dispatchOnStack);
    assignAction(a2m('R'), dispatchOnStack);
    assignAction(a2m('S'), dispatchOnStack);
    assignAction(a2m('T'), dispatchOnStack);
    assignAction(a2m('U'), txUptime);
    assignAction(a2m('V'), dispatchOnStack);
    assignAction(a2m('X'), dispatchOnStack);
    assignAction(MorseToken(MORSE_AR), dispatchOnStack);
    assignAction(MorseToken(MORSE_AS), dispatchOnStack);
    assignAction(MorseToken(MORSE_SS), dispatchOnStack);
 #if defined(PDA)
    assignAction(MorseToken(MORSE_CT), keyboardMode);
 #endif
    assignAction(MorseToken(MORSE_INTER), dispatchOnStack);
    if (Serial) {
       printBanner();
    }
    uint32_t u;
    (void) EEPROM_readAnything(0, u);
    setUptime(u, true);
    txString("K");
    Serial.setTimeout(3 * 1000);
 }