Didah Morse Code PDA/Appliance: libmorse.h File Reference
libmorse.h File Reference
Morse code operations.
#include "binconst.h"
#include <cstdio>
#include <cstring>
#include <cinttypes>
#include <climits>
#include "teensy3_morse_bsp.h"
#include "morse_token.h"
Functions
Copying the user
bool isIdle ()
Has it been at least 600 word gaps since the last activity?
bool letterExpired ()
Returns true if longer than 5 units have elapsed.
bool wordExpired ()
Has it been long enough that the word under construction should be considered complete?
MorseToken getMorse ()
Accumulate a Morse token.
void flushTouch ()
On my hardware there is cross-coupling between the serial port and the touch sensors. Without the code below, long messages to the serial port trigger a touch input.
Transmission
void txLiteral (MorseToken code)
Transmit a literal Morse code value.
void txError ()
Transmit a Morse code prosign indicating an error. 8 dits.
void txLetter (char a)
Convert an ASCII character into Morse code and transmit it.
void txUnsigned (uint16_t n)
Transmit an unsigned integer in Morse code.
void txTimeHHMM (MorseToken code)
Transmit the 24-hr time.
void txString (const char *s)
Serial I/O
void keyboardMode (MorseToken)
void rxString (char *buffer, size_t n)
template<typename T >
void printLabelValueUnits (const char *label, const T value, const char *units="")
Variables
Morse Code
const int ditFactor = 1
A dit lasts one unit of time.
const int dahFactor = 3
The dah duration is this factor times the dit duration.
const int letterGapFactor = 3
The inter-letter gap is this factor times the dit duration.
const int wordGapFactor = 7
The inter-word gap is this factor times the dit duration.
const char * morsePunctuation
Detailed Description
Morse code operations.
Definition in file libmorse.h.
Function Documentation
MorseToken getMorse ()
Accumulate a Morse token.
If the token is in progress, return an invalid token. If the token is complete, return it. The caller is expected to call this function repeatedly until a token is completed or until the caller decides to stop for some other reason, e.g. timeout.
The two buttons function like an iambic keyer. Since a dit or dah is echoed after it is keyed in, and during this time the application is not listening or buffering, there's no need for additional debouncing logic.
Definition at line 40 of file libmorse.cpp.
References dahPin, ditPin, getTxHz(), setTxHz(), sinceTouch, touchPoll(), txError(), txLetter(), txTick(), and wordExpired().
Referenced by loop(), matchScore(), and rxString().
                       {
   bool ePin(touchPoll(ditPin));
   bool tPin(touchPoll(dahPin));
   if (ePin || tPin) {
     sinceTouch = 0;
     ++touchCount;
   }
   uint32_t saveTxHz(getTxHz());
   // Set the pitch to A#4 for user transmission.
   setTxHz(466);
   if (ePin && !tPin) { // Touching only E...
     txLetter('E');     // A single dit
     leftCode <<= 1;
   }
   if (!ePin && tPin) { // Touching only T...
     txLetter('T');     // A single dah
     leftCode = leftCode << 1 | 1;
   }
   if (ePin && tPin) { // Touching both E and T...
     if (leftCode & 1) {
       txLetter('E');     // A single dit
       leftCode <<= 1;
       ++touchCount;
     }
     txLetter('T');     // A single dah
     leftCode = leftCode << 1 | 1;
   }
   if (wordBits <= touchCount) {
     txError();
     touchCount = 0;
     leftCode = 1;
     sinceTouch = 0;
   }
   // Set the pitch to A4 for the system transmission.
   setTxHz(saveTxHz);
   // End of word timeout...
   if (leftCode != 1 && wordExpired()) {
     txTick(MorseToken());
     // Convert leftCode to rightCode by shifting and adding a sentinel
     // in the (new) left-most bit position.
     MorseToken
       rightCode((leftCode << 1 | 1) << (wordBits - touchCount - 1));
     touchCount = 0;
     leftCode = 1;
     return rightCode;
   } else if (touchCount == 0 && wordExpired()) {
     return MorseToken(1);
   } else {
     return MorseToken();
   }
 }
void rxString (char * buffer, size_t n)
Receive keying into buffer until AR prosign is received, timeout, or buffer full.
Note
n should be positive. If n == 0, a null will be written to buffer[0] and the function will return immediately.
Definition at line 392 of file libmorse.cpp.
References getDitMicros(), getMorse(), MORSE_AR, txString(), and txTock().
Referenced by dispatchOnStack().
{
    char* p(buffer);
    const char* e(buffer + n - 1);
    bool didSpace(true);
    elapsedMicros sinceKeyboard(0);
    char c0(' ');
    char c1(' ');
    MorseToken ar(MORSE_AR);
    for (MorseToken m(getMorse()); p < e &&  m != ar; m = getMorse()) {
       if (m.valid()) {
          const char c(m.toChar());
          if (c0 == ' ' &&
              c1 == '?' &&
              (c == 'V' || c == 'F' || c == 'C' || c == 'T'))
          {
             // Convert " ?V" to " %V" so that voltage is substituted
             // on transmission. Likewise for ?C, ?F, and ?T.
             *(p - 1) = '%';
             Serial.print('%');
          }
          *p++ = c;
          c0 = c1;
          c1 = c;
          Serial.print(c);
          didSpace = false;
          sinceKeyboard = 0;
       } else if (m.pause() &&
                  (20U * getDitMicros() < sinceKeyboard) && !didSpace)
          {
             txTock(MorseToken());
             c0 = c1;
             c1 = ' ';
             *p++ = ' ';
             Serial.print(' ');
             didSpace = true;
          } else if (m.pause() && (200U * getDitMicros() < sinceKeyboard)) {
             Serial.println("Timeout");
             break;
          }
    }
    *p = 0;
    if (p == e) {
       txString("FULL");
    }
    txString("?");
 }
void txError ()
Transmit a Morse code prosign indicating an error. 8 dits.
Transmit a Morse code prosign indicating an error. 8 dits.
Definition at line 114 of file libmorse.cpp.
References txString().
Referenced by askNext(), dispatchOnStack(), exchangeStack(), getFormatForState(), getMorse(), gradeSum(), m2i(), playNote(), playSoundEffect(), restoreActions(), speedUp(), txAlphabetSong(), txAlphaNNN(), txLetter(), txLiteral(), and txMetronome().
                {
   Serial.print("Error [........] ");
   txString("EEEEEEEE");
 }
void txLetter (char a)
Convert an ASCII character into Morse code and transmit it.
Transmit a Morse code symbol consisting of one letter or number. The ASCII-to-Morse translation table is represented as an implicit binary tree. See the header file for details.
If x is not in the set [A-Z0-9], transmit an 'error' prosign.
Definition at line 159 of file libmorse.cpp.
References txError(), and txLiteral().
Referenced by getMorse(), txMacAddress(), txString(), and txUnsigned().
                       {
    MorseToken letterCode(a, MorseToken::Char);
    if (letterCode != MORSE_ERROR) {
       txLiteral(letterCode);
    } else {
       txError();
       Serial.println(a);
    }
 }
void txLiteral (MorseToken code)
Transmit a literal Morse code value.
Transmit a Morse code symbol. The parameter is encoded as a left-justified bit sequence where 0 represents dit and 1 represents dah. Since Morse code symbols vary in length, the code is terminated with a 1 after the right- most token.
Definition at line 137 of file libmorse.cpp.
References beep(), dahFactor, ditFactor, getDitMicros(), getTxHz(), letterGapFactor, MORSE_MSB, txError(), and MorseToken::valid().
Referenced by txEcho(), txLetter(), txListSymbolStack(), txString(), and txSymbolStackTop().
{
    if (code.valid()) {      // Guard against an infinite loop.
       uint8_t raw(code);
       while (raw != MORSE_MSB) {
          beep(getTxHz(),
               getDitMicros() * (raw & MORSE_MSB ? dahFactor : ditFactor));
          Serial.print(raw & MORSE_MSB ? "_" : ".");
          delayMicroseconds(getDitMicros());
          raw <<= 1;
       }
       Serial.print(' ');
       delayMicroseconds((letterGapFactor - ditFactor) * getDitMicros());
    } else {
       txError();
    }
 }
void txString (const char * s)
Transmit a string as Morse code. Prosigns are delimited with carets instead of underscores, e.g. "^SOS^ ^SOS^ ^SOS^ DE GBTT GBTT GBTT QUEEN ELIZABETH 2"
Transmit a Morse code string. Prosigns are delimited by carets (^), e.g. "^QTR^ 2112". Caret is used instead of underscore so that underscores can be transmitted without quoting them or encoding them somehow.
Several format placeholders are supported.
C - Transmit the temperature in degrees Celsius
F - Transmit the temperature in degrees Fahrenheit
T - Transmit the 24-hour time as four-digits
U - Transmit the uptime in quarter hours
V - Transmit the millivolts measured by pin analogInput
%% - Transmit a literal percent sign (not that anyone will understand this obscure Morse code)
Abort if the dit key is touched.
Definition at line 208 of file libmorse.cpp.
References dahPin, ditPin, flushTouch(), getDitMicros(), getInternalTemperatureC(), letterGapFactor, readMillivolts(), touchPoll(), txInternalTemperatureF(), txLetter(), txLiteral(), txTimeHHMM(), txUnsigned(), txUptime(), and wordGapFactor.
Referenced by askNext(), askSum(), dispatchOnStack(), getPressure(), gradeSum(), loop(), matchScore(), playSoundEffect(), rxString(), setup(), slowDown(), speedUp(), txAlphabetSong(), txAlphaNNN(), txAR(), txEcho(), txError(), txGreeting(), txHelp(), txMenu(), txSettings(), txTimeHHMM(), and txTimeVerbose().
{
    bool gotPercentSign(false);
    if (*s) {
       for (char* p(const_cast<char*>(s));
            *p && !touchPoll(ditPin) && !touchPoll(dahPin);
            ++p)
          {
             if (*p == ' ') {
                Serial.print('/');
                for (int i(0); i < wordGapFactor; ++i) {
                   delayMicroseconds(getDitMicros());
                   if (touchPoll(ditPin) || touchPoll(dahPin)) {
                      return;
                   }
                }
             } else if (*p == '^') {
                // Accumulate the following prosign and transmit it.
                char pbuffer[5] = { '1', '2', '3', '4', '\0' };
                char* q(pbuffer);
                while (*q && *++p != '^') *q++ = *p;
                *q = 0;
                txLiteral(MorseToken(pbuffer, MorseToken::Prosign));
             } else if (gotPercentSign) {
                switch (*p) {
                case '%': txLetter(*p); break;
                case 'C':
                {
                   uint16_t t(getInternalTemperatureC());
                   txUnsigned(t);
                }
                break;
                case 'F':
                   txInternalTemperatureF(MorseToken());
                   break;
                case 'T': txTimeHHMM(MorseToken()); break;
                case 'U': txUptime(MorseToken()); break;
                case 'V': txUnsigned((uint16_t) readMillivolts()); break;
                default:
                   txLetter('%');
                   txLetter(*p);
                }
                gotPercentSign = false;
             } else if (*p == '%') {
                gotPercentSign = true;
             } else {
                txLetter(*p);
             }
          }
       delayMicroseconds((wordGapFactor - letterGapFactor) * getDitMicros());
       Serial.println();
       Serial.println(s);
       flushTouch();
    }
 }
void txUnsigned (uint16_t n)
Transmit an unsigned integer in Morse code.
Convert an unsigned integer into a sequence of Morse code numerals and transmit them.
Definition at line 170 of file libmorse.cpp.
References dahPin, ditPin, touchPoll(), and txLetter().
Referenced by playNote(), txInternalTemperatureC(), txInternalTemperatureF(), txMetronome(), txSettings(), txString(), and txUptime().
{
   // The constant digits10 below is not the maximum number of digits
   // required to represent the parameter type. Rather, it is the
   // maximum number of digits that can be represented in a variable of
   // the given type without change. E.g. the type char can represent
   // 99, but not 999, so digits10 is 2, not 3, hence we add 1 to store
   // all the digits that could be needed for input argument n.
   char digitBuffer[std::numeric_limits<uint16_t>::digits10 + 1];
   uint16_t digitCount(0);
   do {
     // Convert the least significant digit to ASCII.
     digitBuffer[digitCount++] = '0' + n % 10;
     // Proceed to the next digit.
     n /= 10;
   } while (n);
   while (digitCount && !touchPoll(ditPin) && !touchPoll(dahPin)) {
     txLetter(digitBuffer[--digitCount]);
     Serial.print(digitBuffer[digitCount]);
   }
   Serial.println("");
 }