Didah Morse Code PDA/Appliance: libmorse.cpp File Reference
libmorse.cpp File Reference
Implementation of Morse code operations.
#include <cstring>
#include <limits>
#include "Arduino.h"
#include "libmorse.h"
#include "settings.h"
#include "stack.h"
#include "actions.h"
#include "prosign.h"
#include "Time.h"
Functions
bool isIdle ()
Has it been at least 600 word gaps since the last activity?
bool letterExpired ()
Returns true if longer than 5 units have elapsed.
bool wordExpired ()
Has it been long enough that the word under construction should be considered complete?
MorseToken getMorse ()
Accumulate a Morse token.
void flushTouch ()
On my hardware there is cross-coupling between the serial port and the touch sensors. Without the code below, long messages to the serial port trigger a touch input.
void txError ()
Transmit a Morse code prosign indicating an error.
const char * m2didah (MorseToken code)
Return a string of dots and dashes corresponding to code.
void txLiteral (MorseToken code)
Transmit a literal Morse code value.
void txLetter (char a)
Convert an ASCII character into Morse code and transmit it.
void txUnsigned (uint16_t n)
Transmit an unsigned integer in Morse code.
void txString (const char *s)
uint8_t matchScore (const char *pattern)
Score the given pattern against the state of the symbol stack.
void rxString (char *buffer, size_t n)
Variables
elapsedMicros sinceTouch
uint16_t leftCode = 1
uint8_t touchCount = 0
Detailed Description
Implementation of Morse code operations.
Definition in file libmorse.cpp.
Function Documentation
MorseToken getMorse ()
Accumulate a Morse token.
If the token is in progress, return an invalid token. If the token is complete, return it. The caller is expected to call this function repeatedly until a token is completed or until the caller decides to stop for some other reason, e.g. timeout.
The two buttons function like an iambic keyer. Since a dit or dah is echoed after it is keyed in, and during this time the application is not listening or buffering, there's no need for additional debouncing logic.
Definition at line 40 of file libmorse.cpp.
References dahPin, ditPin, getTxHz(), setTxHz(), sinceTouch, touchPoll(), txError(), txLetter(), txTick(), and wordExpired().
Referenced by matchScore(), and rxString().
                       {
   bool ePin(touchPoll(ditPin));
   bool tPin(touchPoll(dahPin));
   if (ePin || tPin) {
     sinceTouch = 0;
     ++touchCount;
   }
   uint32_t saveTxHz(getTxHz());
   // Set the pitch to A#4 for user transmission.
   setTxHz(466);
   if (ePin && !tPin) { // Touching only E...
     txLetter('E');     // A single dit
     leftCode <<= 1;
   }
   if (!ePin && tPin) { // Touching only T...
     txLetter('T');     // A single dah
     leftCode = leftCode << 1 | 1;
   }
   if (ePin && tPin) { // Touching both E and T...
     if (leftCode & 1) {
       txLetter('E');     // A single dit
       leftCode <<= 1;
       ++touchCount;
     }
     txLetter('T');     // A single dah
     leftCode = leftCode << 1 | 1;
   }
   if (wordBits <= touchCount) {
     txError();
     touchCount = 0;
     leftCode = 1;
     sinceTouch = 0;
   }
   // Set the pitch to A4 for the system transmission.
   setTxHz(saveTxHz);
   // End of word timeout...
   if (leftCode != 1 && wordExpired()) {
     txTick(MorseToken());
     // Convert leftCode to rightCode by shifting and adding a sentinel
     // in the (new) left-most bit position.
     MorseToken
       rightCode((leftCode << 1 | 1) << (wordBits - touchCount - 1));
     touchCount = 0;
     leftCode = 1;
     return rightCode;
   } else if (touchCount == 0 && wordExpired()) {
     return MorseToken(1);
   } else {
     return MorseToken();
   }
 }
uint8_t matchScore (const char * pattern)
Score the given pattern against the state of the symbol stack.
The maximum score is 255 and decreases with increased distance from the pattern.
A-Z, 0-9, punctuation - Match a literal character
^CQ^ - Match a prosign
space - Match a word-length or greater pause
a - Match a single letter from A-Z
c - Match any character
d - Match a single digit
n - Match a contiguous sequence of digits
With the exception of n, all the pattern elements match one Morse token. The following punctuation is accepted:
!"$&'()+,-./:;=?@_
The pattern is compared to the stack starting at the end of the pattern and the top of the stack. There is no support for backtracking. All pattern elements are greedy.
Definition at line 265 of file libmorse.cpp.
References getDitMicros(), getMorse(), MORSE_AR, MORSE_BT, s(), symbolStackSize(), txString(), and txTock().
Referenced by dispatchOnStack().
{
    uint8_t score(255);
    const char* patEnd(pattern);
    while (*patEnd) ++patEnd;
    const char* patSym(patEnd);
    if (patSym == pattern) {
       score = 0;
       // Null pattern never matches.
       return score;
    }
    --patSym;
    size_t sp(0);
    bool sawDigit(false);
    do {
       char si(s(sp).toChar());
       switch (*patSym) {
       case 'a':
          // Match any (simple greedy match).
          // Must occur at the beginning of the pattern.
          return score;
          break;
       case 'c':
          // Match a character.
          score -= score && !isalnum(si);
          break;
       case 'd':
          // Match a digit.
          score -= score && (uint8_t(9U) < uint8_t(si - '0'));
          break;
       case 'n':
          // Match one or more digits.
          // Note: only the stack size limits the number of digits.
          if (uint8_t(si - '0') < 10U) {
             sawDigit = true;
             // Don't advance to the next character of pattern.
             ++patSym;
          } else {
             if (!sawDigit) {
                score -= !!score;
             } else {
                // Finished matching n. Advance the pattern, but reuse
                // the current stack element.
                --sp;
             }
          }
          break;
       case '^': {
          // Match a prosign.
          // Note: This code is just enough different than txString to
          // be annoying.
          char pbuffer[5] = { '1', '2', '3', '4', '\0' };
          char* pb(pbuffer);
          --patSym;
          while (*patSym && (*patSym != '^')) {
             *pb++ = *patSym--;
          }
          --patSym;
          *pb-- = 0;
          // Reverse pbuffer since we're matching backwards, but the
          // prosign is a single multi-character entity.
          char* fb(pbuffer);
          while (fb < pb) {
             char temp(*fb);
             *fb++ = *pb;
             *pb-- = temp;
          }
          score -= score &&
             uint8_t(MorseToken(pbuffer, MorseToken::Prosign)) != s(sp);
          break;
       }
       default:
          // Match the literal value of c.
          score -= score && si != uint8_t(*patSym);
       };
    } while (pattern < patSym-- && ++sp != symbolStackSize());
    if (pattern != patSym && sp == symbolStackSize()) {
       // If the pattern wasn't used completely deduct a point for
       // ever unused pattern symbol.
       score -= patSym - pattern;
    }
    return score;
 }
void rxString (char * buffer, size_t n)
Receive keying into buffer until AR prosign is received, timeout, or buffer full.
Note
n should be positive. If n == 0, a null will be written to buffer[0] and the function will return immediately.
Definition at line 392 of file libmorse.cpp.
References getDitMicros(), getMorse(), MORSE_AR, txString(), and txTock().
Referenced by dispatchOnStack().
{
    char* p(buffer);
    const char* e(buffer + n - 1);
    bool didSpace(true);
    elapsedMicros sinceKeyboard(0);
    char c0(' ');
    char c1(' ');
    MorseToken ar(MORSE_AR);
    for (MorseToken m(getMorse()); p < e &&  m != ar; m = getMorse()) {
       if (m.valid()) {
          const char c(m.toChar());
          if (c0 == ' ' &&
              c1 == '?' &&
              (c == 'V' || c == 'F' || c == 'C' || c == 'T'))
          {
             // Convert " ?V" to " %V" so that voltage is substituted
             // on transmission. Likewise for ?C, ?F, and ?T.
             *(p - 1) = '%';
             Serial.print('%');
          }
          *p++ = c;
          c0 = c1;
          c1 = c;
          Serial.print(c);
          didSpace = false;
          sinceKeyboard = 0;
       } else if (m.pause() &&
                  (20U * getDitMicros() < sinceKeyboard) && !didSpace)
          {
             txTock(MorseToken());
             c0 = c1;
             c1 = ' ';
             *p++ = ' ';
             Serial.print(' ');
             didSpace = true;
          } else if (m.pause() && (200U * getDitMicros() < sinceKeyboard)) {
             Serial.println("Timeout");
             break;
          }
    }
    *p = 0;
    if (p == e) {
       txString("FULL");
    }
    txString("?");
 }
void txError ()
Transmit a Morse code prosign indicating an error.
Transmit a Morse code prosign indicating an error. 8 dits.
Definition at line 114 of file libmorse.cpp.
References txString().
Referenced by askNext(), dispatchOnStack(), exchangeStack(), getFormatForState(), getMorse(), gradeSum(), m2i(), playNote(), playSoundEffect(), restoreActions(), speedUp(), txAlphabetSong(), txAlphaNNN(), txLetter(), txLiteral(), and txMetronome().
                {
   Serial.print("Error [........] ");
   txString("EEEEEEEE");
 }
void txLetter (char a)
Convert an ASCII character into Morse code and transmit it.
Transmit a Morse code symbol consisting of one letter or number. The ASCII-to-Morse translation table is represented as an implicit binary tree. See the header file for details.
If x is not in the set [A-Z0-9], transmit an 'error' prosign.
Definition at line 159 of file libmorse.cpp.
References txError(), and txLiteral().
Referenced by getMorse(), txMacAddress(), txString(), and txUnsigned().
                       {
    MorseToken letterCode(a, MorseToken::Char);
    if (letterCode != MORSE_ERROR) {
       txLiteral(letterCode);
    } else {
       txError();
       Serial.println(a);
    }
 }
void txLiteral (MorseToken code)
Transmit a literal Morse code value.
Transmit a Morse code symbol. The parameter is encoded as a left-justified bit sequence where 0 represents dit and 1 represents dah. Since Morse code symbols vary in length, the code is terminated with a 1 after the right- most token.
Definition at line 137 of file libmorse.cpp.
References beep(), dahFactor, ditFactor, getDitMicros(), getTxHz(), letterGapFactor, MORSE_MSB, txError(), and MorseToken::valid().
Referenced by txEcho(), txLetter(), txListSymbolStack(), txString(), and txSymbolStackTop().
{
    if (code.valid()) {      // Guard against an infinite loop.
       uint8_t raw(code);
       while (raw != MORSE_MSB) {
          beep(getTxHz(),
               getDitMicros() * (raw & MORSE_MSB ? dahFactor : ditFactor));
          Serial.print(raw & MORSE_MSB ? "_" : ".");
          delayMicroseconds(getDitMicros());
          raw <<= 1;
       }
       Serial.print(' ');
       delayMicroseconds((letterGapFactor - ditFactor) * getDitMicros());
    } else {
       txError();
    }
 }
void txString (const char * s)
Transmit a Morse code string. Prosigns are delimited by carets (^), e.g. "^QTR^ 2112". Caret is used instead of underscore so that underscores can be transmitted without quoting them or encoding them somehow.
Several format placeholders are supported.
C - Transmit the temperature in degrees Celsius
F - Transmit the temperature in degrees Fahrenheit
T - Transmit the 24-hour time as four-digits
U - Transmit the uptime in quarter hours
V - Transmit the millivolts measured by pin analogInput
%% - Transmit a literal percent sign (not that anyone will understand this obscure Morse code)
Abort if the dit key is touched.
Definition at line 208 of file libmorse.cpp.
References dahPin, ditPin, flushTouch(), getDitMicros(), getInternalTemperatureC(), letterGapFactor, readMillivolts(), touchPoll(), txInternalTemperatureF(), txLetter(), txLiteral(), txTimeHHMM(), txUnsigned(), txUptime(), and wordGapFactor.
Referenced by askNext(), askSum(), dispatchOnStack(), getPressure(), gradeSum(), matchScore(), playSoundEffect(), rxString(), slowDown(), speedUp(), txAlphabetSong(), txAlphaNNN(), txAR(), txEcho(), txError(), txGreeting(), txHelp(), txMenu(), txSettings(), txTimeHHMM(), and txTimeVerbose().
{
    bool gotPercentSign(false);
    if (*s) {
       for (char* p(const_cast<char*>(s));
            *p && !touchPoll(ditPin) && !touchPoll(dahPin);
            ++p)
          {
             if (*p == ' ') {
                Serial.print('/');
                for (int i(0); i < wordGapFactor; ++i) {
                   delayMicroseconds(getDitMicros());
                   if (touchPoll(ditPin) || touchPoll(dahPin)) {
                      return;
                   }
                }
             } else if (*p == '^') {
                // Accumulate the following prosign and transmit it.
                char pbuffer[5] = { '1', '2', '3', '4', '\0' };
                char* q(pbuffer);
                while (*q && *++p != '^') *q++ = *p;
                *q = 0;
                txLiteral(MorseToken(pbuffer, MorseToken::Prosign));
             } else if (gotPercentSign) {
                switch (*p) {
                case '%': txLetter(*p); break;
                case 'C':
                {
                   uint16_t t(getInternalTemperatureC());
                   txUnsigned(t);
                }
                break;
                case 'F':
                   txInternalTemperatureF(MorseToken());
                   break;
                case 'T': txTimeHHMM(MorseToken()); break;
                case 'U': txUptime(MorseToken()); break;
                case 'V': txUnsigned((uint16_t) readMillivolts()); break;
                default:
                   txLetter('%');
                   txLetter(*p);
                }
                gotPercentSign = false;
             } else if (*p == '%') {
                gotPercentSign = true;
             } else {
                txLetter(*p);
             }
          }
       delayMicroseconds((wordGapFactor - letterGapFactor) * getDitMicros());
       Serial.println();
       Serial.println(s);
       flushTouch();
    }
 }
void txUnsigned (uint16_t n)
Transmit an unsigned integer in Morse code.
Convert an unsigned integer into a sequence of Morse code numerals and transmit them.
Definition at line 170 of file libmorse.cpp.
References dahPin, ditPin, touchPoll(), and txLetter().
Referenced by playNote(), txInternalTemperatureC(), txInternalTemperatureF(), txMetronome(), txSettings(), txString(), and txUptime().
{
   // The constant digits10 below is not the maximum number of digits
   // required to represent the parameter type. Rather, it is the
   // maximum number of digits that can be represented in a variable of
   // the given type without change. E.g. the type char can represent
   // 99, but not 999, so digits10 is 2, not 3, hence we add 1 to store
   // all the digits that could be needed for input argument n.
   char digitBuffer[std::numeric_limits<uint16_t>::digits10 + 1];
   uint16_t digitCount(0);
   do {
     // Convert the least significant digit to ASCII.
     digitBuffer[digitCount++] = '0' + n % 10;
     // Proceed to the next digit.
     n /= 10;
   } while (n);
   while (digitCount && !touchPoll(ditPin) && !touchPoll(dahPin)) {
     txLetter(digitBuffer[--digitCount]);
     Serial.print(digitBuffer[digitCount]);
   }
   Serial.println("");
 }
Variable Documentation
elapsedMicros sinceTouch
The end of the user's input is determined by a timeout equal to two times the normal word gap.
Definition at line 17 of file libmorse.cpp.
Referenced by flushTouch(), getMorse(), isIdle(), letterExpired(), and wordExpired().