Didah Morse Code PDA/Appliance: morse_digit.cpp File Reference
morse_digit.cpp File Reference
Implementation of decimal digit to Morse code conversion.
#include "teensy3_morse_bsp.h"
#include "settings.h"
#include "actions.h"
#include "morse_digit.h"
Functions
void blinkMorseDigit (uint8_t digit)
void bmd096 (uint8_t digit)
void bmd104 (uint8_t digit)
Detailed Description
Implementation of decimal digit to Morse code conversion.
Definition in file morse_digit.cpp.
Function Documentation
void blinkMorseDigit (uint8_t digit)
Transmit a digit in Morse code for memory-limited applications. This wacky stand-alone function for blinking out a single digit from 0-9 in Morse code.
The function uses a single eight bit constant 0b111110 with arithmetic shifts as the Morse code table for the 10 values,
The function depends on sign extension, and
The function fits in 80 bytes of ARM code.
Parameters
digit is the actual digit 0-9, not ASCII.
Morse code for the digits:
Digit Morse Code Binary
0 ----- 11111
1 .---- 01111
2 ..--- 00111
3 ...-- 00011
4 ....- 00001
5 ..... 00000
6 -.... 10000
7 --... 11000
8 ---.. 11100
9 ----. 11110
This is a standalone function. It does not use the left-justified encoding scheme described in the header file.
This routine takes 80 bytes.
I imagine this function as the gateway drug of Morse code debugging.
Definition at line 8 of file morse_digit.cpp.
References beep(), dahFactor, ditFactor, getDitMicros(), letterGapFactor, and wordGapFactor.
{
   const signed char b111110(0x3E);
   const signed char dend(digit - 5);
   for (signed char i(digit); i != dend; --i) {
     beep(440,
      getDitMicros() * (b111110 >> i & 1 ? ditFactor : dahFactor));
     delayMicroseconds(getDitMicros() *
               (i - 1 == dend ? letterGapFactor : wordGapFactor));
   }
 }
void bmd096 (uint8_t digit)
Blink a single Morse code digit. Implemented with a table lookup. 96 bytes
Definition at line 22 of file morse_digit.cpp.
References B8, beep(), dahFactor, ditFactor, getDitMicros(), letterGapFactor, and wordGapFactor.
{
   uint8_t t[] = {
     B8(111111), B8(111110), B8(111100), B8(111000), B8(110000),
     B8(100000), B8(100001), B8(100011), B8(100111), B8(101111)
   };
   uint8_t m(t[digit]);
   while (m != 1) {
     beep(440, getDitMicros() * (m & 1 ? dahFactor : ditFactor));
     delayMicroseconds(getDitMicros() *
                       (m != 1 ? letterGapFactor : wordGapFactor));
     m >>= 1;
   }
 }
void bmd104 (uint8_t digit)
Blink a single Morse code digit. Implemented implemented with a table lookup and the observation that Morse(x) == ~Morse(x + 5) when x < 5. 104 bytes
Definition at line 40 of file morse_digit.cpp.
References B8, beep(), dahFactor, ditFactor, getDitMicros(), letterGapFactor, and wordGapFactor.
{
   uint8_t t[] = { B8(11111), B8(11110), B8(11100), B8(11000), B8(10000) };
   uint8_t m(digit < 6 ? t[digit] : t[digit - 5] ^ B8(11111));
   m |= 1 << 5;
   while (m != 1) {
     beep(440, getDitMicros() * (m & 1 ? dahFactor : ditFactor));
     delayMicroseconds(getDitMicros() *
               (m != 1 ? letterGapFactor : wordGapFactor));
     m >>= 1;
   }
 }