Didah Morse Code PDA/Appliance: morse_token.h File Reference
morse_token.h File Reference
Defines the MorseToken class and various helpers.
#include <cinttypes>
#include <climits>
#include <cstddef>
#include "prosign.h"
Classes
class MorseToken
Represents an individual Morse code token, such as a letter, pause, or prosign.
Macros
#define MORSE_MSB (1 << (CHAR_BIT * sizeof MorseToken(0) - 1))
Mask for the high order bit of a MorseToken field.
Functions
char m2a (MorseToken code)
Convert a Morse code into ASCII.
MorseToken a2m (char a)
Convert a single ASCII character into a Morse code token.
uint8_t m2i (MorseToken m)
Convert Morse 0-9 to the corresponding digit.
MorseToken a2p (const char *prosign)
const size_t wordBits (CHAR_BIT *sizeof MorseToken())
Detailed Description
Defines the MorseToken class and various helpers.
Each Morse code symbol is encoded as a bit vector, processed from MSB to LSB with 0 corresponding to dit and 1 corresponding to dah. Since Morse code symbols vary in length, a 1 bit follows the last dit/dah and remaining low order bits are all zero. This makes it convenient to serialize a code word by left shifting one bit at a time stopping when the remainder has only the MSB set.
Definition in file morse_token.h.
Function Documentation
MorseToken a2m (char a)
Convert a single ASCII character into a Morse code token.
Convert a single ASCII letter, number, or a few operators to Morse code.
Definition at line 86 of file morse_token.cpp.
References MORSE_AA, MORSE_AMPER, MORSE_MSB, and morseTree.
Referenced by setup().
{
    uint8_t letterCode(0);
    ptrdiff_t key(strchr(morseTree, a) - morseTree);
    if (0 < key && morseTree[key] != MORSE_UNDEFINED_CHAR) {
       // Add the sentinel to the right.
       letterCode = key << 1 | 1;
       while (!(letterCode & MORSE_MSB)) {
          letterCode <<= 1;
       }
       letterCode <<= 1;
    } else {
       // The codes below would require more rows in morseTree and
       // the rows would be mostly empty, so they are handled here.
       switch (a) {
       case '\n': letterCode = MORSE_AA; break;
       case '&':  letterCode = MORSE_AMPER; break;
       case ')':  letterCode = MORSE_CLOSEP; break;
       case '$':  letterCode = MORSE_DOLLAR; break;
       default:
          ; // Nothing more to do since letterCode is initialized to 0
          // (invalid).
       }
    }
    return MorseToken(letterCode);
 }
MorseToken a2p (const char * prosign)
Given an ASCII string representing a prosign, return a code composed by concatenating the morse code for each character in the prosign without inter-symbol gaps.
For example "AB" yields
String Morse Code Binary
A . _ 01100000
B _ . . . 10001000
AB . _ _ . . . 01100010
If the translation is longer than will fit in MorseToken, the return value will be the longest suffix of the input that does fit. All the prosigns I'm aware of fit without truncation if MorseToken is 16 bits or more. Most fit in 7 bits with the notable exception of MORSE_ERROR, which requires 9 bits (8 symbols + 1 sentinel). Unfortunately, there are many ways of denoting 8 dits, so the special case isn't so easy to code, e.g. ^HH^, ^5S^, ^S5^, ^IIII^, ^IIH^, ^EEEEEEEE^, etc.
Definition at line 145 of file morse_token.cpp.
{
    uint8_t letterCode(MorseToken(prosign[0], MorseToken::Char));
    uint8_t t(letterCode);
    size_t length(0);
    while (t) { ++length; t <<= 1; }
    const char* p(prosign + 1);
    while (*p) {
       char a(*p);
       uint8_t m(MorseToken(a, MorseToken::Char));
       // Erase the sentinel (always 1).
       letterCode ^= 1 << (wordBits - length);
       // Shift the new symbol and or it in after the previous.
       letterCode |= m >> (length - 1);
       // Update the length.
       while (m) { ++length; m <<= 1; }
       ++p;
    }
    return MorseToken(letterCode);
 }
char m2a (MorseToken code)
Convert a Morse code into ASCII.
Convert Morse code (internal notation: reversed right justified with sentinel on the left) to ASCII.
Definition at line 46 of file morse_token.cpp.
References MORSE_MSB, MORSE_SS, morseTree, MorseToken::pause(), and MorseToken::valid().
Referenced by MorseToken::toChar().
{
    char result('x');
    if (!code.valid()) {
       ; // Return 'x' for error.
    } else if (code.pause()) {
       result = ' ';
    } else {
       int length(-2);
       uint8_t t(MORSE_MSB | (code >> 1));
       while (t) {
          t <<= 1;
          ++length;
       }
       uint8_t raw(code);
       raw >>= (CHAR_BIT * sizeof MorseToken(0) - length);
       raw |= 1 << length;
       // Translate the subset of the prosigns/abbreviations that can
       // be represented by a single ASCII character, but are not
       // present in morseTree. These tokens have 7 symbols. Dollary
       // sign is recognized as a six symbol prefix of its seven symbol
       // code.
       //
       // Note: MORSE_ERROR does not fit in the 8-bit representation of
       // MorseToken.
       switch (raw) {
       case MORSE_DOLLAR: result = '$'; break;
       case MORSE_SS:     result = '#'; break;
       default:
          if (raw < sizeof morseTree) {
             result = morseTree[raw];
          } else {
             ; // Nothing more to do since result is initialized to 'x'.
          }
       }
    }
    return result;
 }
uint8_t m2i (MorseToken m)
Convert Morse 0-9 to the corresponding digit.
The given Morse code token should be a digit. Return the corresponding number. If the input is not a digit, transmits the error prosign and returns an undefined value.
Definition at line 115 of file morse_token.cpp.
References MorseToken::toChar(), and txError().
Referenced by gradeSum(), MorseToken::m2i(), playSoundEffect(), stackDigitsToUnsigned(), and txAlphabetSong().
{
   uint8_t result(m.toChar() - '0');
   if (9 < result) {
     txError();
   }
   return result;
 }