Didah Morse Code PDA/Appliance: pda.h File Reference
pda.h File Reference
Personal Digital Assistant functions.
#include "libmorse.h"
Functions
void txTimeHHMM (MorseToken code)
Transmit the 24-hr time.
void pressureTone (uint16_t duration)
void playScale (MorseToken code)
Play a chromatic scale.
void playSoundEffect (MorseToken cord)
Play one of 10 sound effects based on the digit on the stack.
void playNote (MorseToken code)
uint8_t durationDits (char a)
void txAlphabetSong (MorseToken code)
void txAlfaBravoCharlie (MorseToken code)
void txAlfaNNN (MorseToken code)
void askSum (MorseToken)
void gradeSum (MorseToken)
void askNext (MorseToken)
void askNextAlfa (MorseToken)
void gradeRestore (MorseToken answer)
void gradeNext (MorseToken)
void txMetronome (MorseToken)
void sumStack (MorseToken)
void guitarTune (MorseToken)
void setAlarm (MorseToken)
Detailed Description
Personal Digital Assistant functions.
Definition in file pda.h.
Function Documentation
void askNext (MorseToken)
Prompt with a random letter of the alphabet. The user enters the letter then enters I to get graded.
Definition at line 595 of file pda.cpp.
References assignAction(), popSymbolStack(), push1RestoreAll(), pushSymbolStack(), s(), saveActions(), symbolStackSize(), txError(), txString(), and txSymbolStackTop().
{
    uint8_t a(random(26));
    char buffer[3] = { char(a + 'A'), 0 };
    txString(buffer);
    uint8_t b((a + 1) % 26);
    pushSymbolStack(MorseToken(b + 'A', MorseToken::Char));
    assignAction(MorseToken('I', MorseToken::Char), gradeNext);
    saveActions();
    for (size_t i('A'); i <= 'Z' ; ++i) {
       assignAction(MorseToken(i, MorseToken::Char), push1RestoreAll);
    }
 }
void askNextAlfa (MorseToken)
This is a little harder than askNext in that the extra letters can be distracting, but it is a little easier because there's more context. I expect that for beginners, the former is easier, but for intermediates, the latter is good practice.
Definition at line 370 of file pda.cpp.
References assignAction(), push1RestoreAll(), pushSymbolStack(), and saveActions().
{
    uint8_t a(random(26));
    txAlfaBravoCharlie(MorseToken(a + 'A', MorseToken::Char));
    uint8_t b((a + 1) % 26);
    pushSymbolStack(MorseToken(b + 'A', MorseToken::Char));
    assignAction(MorseToken('I', MorseToken::Char), gradeNext);
    saveActions();
    for (size_t i('A'); i <= 'Z' ; ++i) {
       assignAction(MorseToken(i, MorseToken::Char), push1RestoreAll);
    }
 }
void askSum (MorseToken)
Present a simple challenge consisting of two random digits to add. The user tries to enter the last digit of their sum.
Definition at line 504 of file pda.cpp.
References assignAction(), getDigitByWeight(), pushSymbolStack(), saveActions(), and txString().
{
    uint8_t a(getDigitByWeight());
    uint8_t b(getDigitByWeight());
    char buffer[3] = { char(a + '0'), char(b + '0'), 0 };
    txString(buffer);
    pushSymbolStack(MorseToken(buffer[0], MorseToken::Char));
    pushSymbolStack(MorseToken(buffer[1], MorseToken::Char));
    saveActions();
    for (size_t i('0'); i <= '9' ; ++i) {
       assignAction(MorseToken(i, MorseToken::Char), gradeRestore);
    }
 }
uint8_t durationDits (char a)
Return the duration of the Morse code for the given character in dits. E.g. an E would return 2; and an N would return 6.
Definition at line 272 of file pda.cpp.
References dahFactor, ditFactor, MORSE_MSB, and wordGapFactor.
Referenced by txAlphabetSong().
{
    if (a == ' ') {
       return wordGapFactor;
    } else {
       uint8_t code(MorseToken(a, MorseToken::Char));
       uint8_t count(0);
       while (code != MORSE_MSB) {
          count += ((code & MORSE_MSB) ? dahFactor : ditFactor) + ditFactor;
          code <<= 1;
       }
       return count;
    }
 }
void gradeSum (MorseToken)
The top three entries on the stack are two digits to add and their proported sum mod 10. Transmit Y/N to indicate whether or not the sum is correct. If the sum is not correct, transmit the correct sum. Update the weights to bias future random number selection.
Definition at line 521 of file pda.cpp.
References digitErr, digitErrCount(), m2i(), popN(), s(), symbolStackSize(), txError(), and txString().
Referenced by getDigitByWeight().
{
   if (2 < symbolStackSize()) {
     uint8_t s1(s(1).m2i());
     uint8_t s2(s(2).m2i());
     uint8_t s0(s(0).toChar());
     uint8_t sum((s1 + s2) % 10);
     Serial.print(s2);
     Serial.print(" ");
     Serial.print(s1);
     Serial.print(" ");
     Serial.print(s0);
     Serial.print(" sum: ");
     Serial.println(sum);
     bool correct(s(0).m2i() == sum);
     if (correct) {
       txString("Y");
       // Decrease the error counts associated with the digits the user
       // just added incorrectly, taking care not to underflow.
       uint8_t d1(!!digitErr[s1]);
       uint8_t d2(!!digitErr[s2]);
       digitErr[s1] -= d1;
       digitErr[s2] -= d2;
       digitErrCount -= (d1 + d2);
       Serial.print("Decrementing ");
       Serial.print(s1);
       Serial.print(". New weight is: ");
       Serial.println(digitErr[s1]);
       Serial.print("Decrementing ");
       Serial.print(s2);
       Serial.print(". New weight is: ");
       Serial.println(digitErr[s2]);
     } else {
       //            012345678901
       char buffer[] = "N  a + b = c";
       buffer[3] = s2 + '0';
       buffer[7] = s1 + '0';
       buffer[11] = sum + '0';
       txString(buffer);
       // Increase the error counts associated with the digits the user
       // just added incorrectly, taking care not to overflow.
       uint8_t d1(3 * (digitErr[s1] - 3 < 255));
       uint8_t d2(3 * (digitErr[s2] - 3 < 255));
       digitErr[s1] += d1;
       digitErr[s2] += d2;
       digitErrCount += d1 + d2;
       Serial.print("Incrementing ");
       Serial.print(s1);
       Serial.print(". New weight is: ");
       Serial.println(digitErr[s1]);
       Serial.print("Incrementing ");
       Serial.print(s2);
       Serial.print(". New weight is: ");
       Serial.println(digitErr[s2]);
     }
     // If the user plays long enough without a reset to saturate two
     // of the digits chosen at random, divide all the error counts
     // by 2.
     if (digitErr[s1] == 255 && digitErr[s2] == 255) {
       for (uint8_t i(0); i < 10; ++i) {
     digitErr[i] <<= 1;
       }
       digitErrCount <<= 1;
       Serial.println("Halving all weights.");
     }
     Serial.print("Digit error count is: ");
     Serial.println(digitErrCount);
     popN(3);
   } else {
     txError();
   }
 }
void playNote (MorseToken)
If the top two elements of the stack are digits, convert them to a number between 0-99 inclusive. Play the corresponding note.
Definition at line 260 of file pda.cpp.
References getDitMicros(), noteHz, playTone(), s(), symbolStackSize(), txError(), and txUnsigned().
{
   if (1 < symbolStackSize() && isdigit(s(0).toChar()) && isdigit(s(1).toChar())) {
     size_t note(10 * (s(1).toChar() - '0') + (s(0).toChar() - '0'));
     playTone(noteHz[note] + 0.5, getDitMicros() * 60);
     txUnsigned(note);
   } else {
     txError();
   }
 }
void pressureTone (uint16_t duration)
Play a series of tones randomly bounded by the reading of the dit pin.
Definition at line 111 of file pda.cpp.
References ditPin, and dWrite().
{
   elapsedMicros t(0);
   while (t < duration) {
     for (int i(1); i < 50; ++i) {
       dWrite(HIGH);
       delayMicroseconds((500 + random(log(touchRead(ditPin)))));
       dWrite(LOW);
       delayMicroseconds((500 + random(log(touchRead(ditPin)))));
     }
   }
 }
void txAlphabetSong (MorseToken)
Play the A.B.C's with each single syllable letter replaced by the corresponding Morse code. W is transmitted once for each syllable. After Z, the remainder of the song is played as simple tones.
Definition at line 289 of file pda.cpp.
References durationDits(), getDitMicros(), getTxHz(), MorseToken::m2i(), m2i(), noteHz, playTone(), popN(), s(), setDitMicros(), setTxHz(), symbolStackSize(), txError(), and txString().
{
   uint32_t saveHz(getTxHz());
   int saveDitMicros(getDitMicros());
   const char* letters("ABCDEFGHIJKLMNOPQRSTUVWWWXY Z ");
   const char*
     notes("C42C42G42G42" "A52A52G44" "F42F42E42E42" "D41D41D41D41C44"
       "G42G42F44"    "E42E42D44" "G41G41G42F44" "E42E42D44"
       "C42C42G42G42" "A52A52G44" "F42F42E42E42" "D42D42C44");
   char* l(const_cast<char*>(letters));
   char* p(const_cast<char*>(notes));
   while (*p) {
     size_t steps[] = { 0, 2, 3, 5, 7, 8, 10 };
     size_t note(steps[p[0] - 'A'] + 12 * (p[1]-'0'));
     size_t frequency(noteHz[note] + 0.5);
     size_t duration(saveDitMicros * (p[2] - '0') * 2 / 3);
     char buffer[] = { '\0', ' ', '\0' };
     buffer[0] = l[0];
     if (l[1]) {
       setTxHz(frequency);
       setDitMicros(duration);
       txString(buffer);
       delayMicroseconds((14 * saveDitMicros + 1) -
             (saveDitMicros * durationDits(l[0])));
       ++l;
     } else {
       // This part goes much faster, but it doesn't convey much
       // information.
       playTone(frequency, duration);
     }
     p += 3;
   }
   setTxHz(saveHz);
   setDitMicros(saveDitMicros);
 }
void txMetronome (MorseToken)
Note: Since txTick() takes a significant amount of time, the fastest the metronome will currently go is 240 bpm.
Definition at line 419 of file pda.cpp.
References dahPin, getDitMicros(), MorseToken::m2i(), noteHz, playTone(), popN(), s(), symbolStackSize(), touchPoll(), txError(), txTick(), and txUnsigned().
{
   uint8_t bpm(60);
   switch (symbolStackSize()) {
   case 3:
     bpm = 100 * s(2).m2i() + 10 * s(1).m2i() + s(0).m2i();
     popN(3);
     break;
   case 2:
     bpm = 10 * s(1).m2i() + s(0).m2i();
     popN(2);
     break;
   case 1:
     bpm = s(0).m2i();
     popN(1);
     break;
   default: txError();
   }
   uint32_t timeout(60 * 1000000 / bpm);
   elapsedMicros sinceTick(0);
   while (!touchPoll(dahPin)) {
     if (timeout < sinceTick) {
       sinceTick = 0;
       txTick(MorseToken());
     }
   }
 }