Didah Morse Code PDA/Appliance: settings.h File Reference
settings.h File Reference
User settings.
Functions
const uint32_t getRadioStartupDelay ()
Enable the radio transmitter for 120 ms before transmitting.
const int32_t getLowVoltageThresholdDefault ()
The default low-voltage threshold is the minimum voltage.
const int32_t getHighVoltageThresholdDefault ()
The default high-voltage threshold is the maximum voltage.
const int32_t getMaximumVoltage ()
const char * getAnnouncementFormatDefault ()
char * getAnnouncementBuffer ()
size_t getAnnouncementBufferSize ()
Returns the buffer size so updates can be done safely.
char * getAlarmLowBuffer ()
size_t getAlarmLowBufferSize ()
Returns the buffer size so updates can be done safely.
char * getAlarmHighBuffer ()
size_t getAlarmHighBufferSize ()
Returns the buffer size so updates can be done safely.
void initSettings ()
Load the settings from non-volatile memory.
void saveSettings ()
Save the settings to non-volatile memory.
uint32_t getTxHz ()
Get the transmission frequency (side tone).
void setTxHz (uint32_t Hz)
Set the transmission frequency (side tone).
void updateUptime ()
If 15 minutes have elapsed since last time, write to EEPROM.
bool isTimeSet ()
void setUptime (uint32_t u, bool initializing=false)
uint32_t getUptime ()
void setLowVoltageThreshold (int32_t v)
Set the low-voltage alarm threshold.
int32_t getLowVoltageThreshold ()
Get the low-voltage alarm threshold.
void setHighVoltageThreshold (int32_t v)
Set the high-voltage alarm threshold.
int32_t getHighVoltageThreshold ()
Get the high-voltage alarm threshold.
uint32_t getDitMicrosDefault ()
Get the default dit duration in microseconds.
void setDitMicros (uint32_t ms)
Set the dit duration in microseconds.
uint32_t getDitMicros ()
Get the dit duration in microseconds.
void setAnnouncementFormat (const char *format)
Set the periodic announcement format.
const char * getAnnouncementFormat ()
Get the periodic announcement format.
void setAnnouncementInterval (uint32_t seconds)
Set the normal announcement interval in seconds.
uint32_t getAnnouncementInterval ()
Get the normal announcement interval in seconds.
void setAlarmLowFormat (const char *format)
Set the format of periodic low-voltage alarm messages.
void setAlarmHighFormat (const char *format)
Set the format of periodic high-voltage alarm messages.
const char * getAlarmLowFormat ()
Get the format of periodic low-voltage alarm messages.
const char * getAlarmHighFormat ()
Get the format of periodic high-voltage alarm messages.
void setAlarmInterval (uint32_t seconds)
Get the repetition inteval in seconds of when in the alarm state.
uint32_t getAlarmInterval ()
Set the repetition inteval in seconds of when in the alarm state.
bool readMessageFormat (char *buffer, size_t bufferSize, const char *prompt)
Get a message format from the serial console.
Detailed Description
User settings.
Definition in file settings.h.
Function Documentation
char* getAlarmHighBuffer ()
Returns a pointer to the alarm buffer template. Used to update the format.
Definition at line 116 of file settings.cpp.
Referenced by readEvalPrint().
{
    return settings.alarmHighFormat;
 }
char* getAlarmLowBuffer ()
Returns a pointer to the alarm buffer template. Used to update the format.
Definition at line 108 of file settings.cpp.
Referenced by readEvalPrint().
{
    return settings.alarmLowFormat;
 }
char* getAnnouncementBuffer ()
Returns a pointer to the announcement buffer template. Used to update the format.
Definition at line 100 of file settings.cpp.
Referenced by readEvalPrint().
{
    return settings.announcementFormat;
 }
const char* getAnnouncementFormatDefault ()
Returns the message format template BAT V MV ? V MV See txString() for a description of the format parameters such as V.
Definition at line 37 of file settings.cpp.
Referenced by readMessageFormat().
{
    return defaultAnnouncementFormat;
 }
const int32_t getMaximumVoltage ()
Get the maximum voltage the appliance is designed to accept. Returns 16000 mV.
Definition at line 27 of file settings.cpp.
Referenced by dispatchOnStack(), and readEvalPrint().
{
    return maximumVoltage;
 }
bool isTimeSet ()
Has the user set the time?
Note
The uptime is only updated when the time is set. This gives the user the opportunity to see the uptime before the first power failure if power is intermittent.
Definition at line 138 of file settings.cpp.
Referenced by printLog().
                  {
    return timeIsSet;
 }
void updateUptime ()
If 15 minutes have elapsed since last time, write to EEPROM.
Until the user sets the time, the uptime stays fixed at whatever value was stored in EEPROM. Once the user sets the time, the value starts updating to EEPROM every 15 minutes. So in the case of intermittent power, this will tell you the duration of the first interval. Which is not a bad thing to know.
Definition at line 144 of file settings.cpp.
References EEPROM_writeAnything(), and uptime.
Referenced by readEvalPrint().
                     {
    if (15 * 60 * 1000000 <= sinceUptime) {
       ++uptime;
       (void) EEPROM_writeAnything(0, uptime);
       sinceUptime = 0;
    }
 }