Didah Morse Code PDA/Appliance: settings.cpp File Reference
settings.cpp File Reference
Implementation of user settings.
#include "EEPROMAnything.h"
Macros
#define defaultAnnouncementFormat "BAT %V MV ? %V MV"
Functions
const uint32_t getRadioStartupDelay ()
Enable the radio transmitter for 120 ms before transmitting.
const int32_t getLowVoltageThresholdDefault ()
The default low-voltage threshold is the minimum voltage.
const int32_t getMaximumVoltage ()
const int32_t getHighVoltageThresholdDefault ()
The default high-voltage threshold is the maximum voltage.
const char * getAnnouncementFormatDefault ()
size_t getAnnouncementBufferSize ()
Returns the buffer size so updates can be done safely.
char * getAnnouncementBuffer ()
size_t getAlarmLowBufferSize ()
Returns the buffer size so updates can be done safely.
char * getAlarmLowBuffer ()
size_t getAlarmHighBufferSize ()
Returns the buffer size so updates can be done safely.
char * getAlarmHighBuffer ()
uint32_t getTxHz ()
Get the transmission frequency (side tone).
void setTxHz (uint32_t Hz)
Set the transmission frequency (side tone).
void initSettings ()
Load the settings from non-volatile memory.
void saveSettings ()
Save the settings to non-volatile memory.
bool timeIsSet (false)
bool isTimeSet ()
void updateUptime ()
If 15 minutes have elapsed since last time, write to EEPROM.
void setUptime (uint32_t u, bool initializing)
uint32_t getUptime ()
void setLowVoltageThreshold (int32_t v)
Set the low-voltage alarm threshold.
int32_t getLowVoltageThreshold ()
Get the low-voltage alarm threshold.
void setHighVoltageThreshold (int32_t v)
Set the high-voltage alarm threshold.
int32_t getHighVoltageThreshold ()
Get the high-voltage alarm threshold.
uint32_t getDitMicrosDefault ()
Get the default dit duration in microseconds.
void setDitMicros (uint32_t ms)
Set the dit duration in microseconds.
uint32_t getDitMicros ()
Get the dit duration in microseconds.
void setAnnouncementFormat (const char *format)
Set the periodic announcement format.
void setAlarmLowFormat (const char *format)
Set the format of periodic low-voltage alarm messages.
void setAlarmHighFormat (const char *format)
Set the format of periodic high-voltage alarm messages.
const char * getAnnouncementFormat ()
Get the periodic announcement format.
const char * getAlarmLowFormat ()
Get the format of periodic low-voltage alarm messages.
const char * getAlarmHighFormat ()
Get the format of periodic high-voltage alarm messages.
void setAlarmInterval (uint32_t seconds)
Get the repetition inteval in seconds of when in the alarm state.
void setAnnouncementInterval (uint32_t seconds)
Set the normal announcement interval in seconds.
uint32_t getAnnouncementInterval ()
Get the normal announcement interval in seconds.
uint32_t getAlarmInterval ()
Set the repetition inteval in seconds of when in the alarm state.
Variables
const uint32_t radioStartupDelay = 120000
Enable the radio transmitter for 120 ms before transmitting.
const uint32_t ditMicrosDefault = 100000
Duration of a dit in microseconds.
const int32_t lowVoltageThresholdDefault = 2700
const int32_t maximumVoltage = 16000
const int32_t highVoltageThresholdDefault = maximumVoltage
const uint32_t defaultAnnouncementInterval = 600
Default announcement interval in seconds.
const uint32_t defaultAlarmInterval = 30
Default alarm interval in seconds.
const uint32_t defaultFrequency = 750
Default transmission frequency in Hz.
struct {
int32_t lowVoltageThreshold = lowVoltageThresholdDefault
int32_t highVoltageThreshold = highVoltageThresholdDefault
uint32_t ditMicros = ditMicrosDefault
Duration of a 'dit' in microseconds.
char announcementFormat [128] = defaultAnnouncementFormat
Format for periodic announcements in an application-specific syntax.
char alarmLowFormat [128] = defaultAnnouncementFormat
Format for periodic announcements when voltage is low.
char alarmHighFormat [128] = defaultAnnouncementFormat
Format for periodic announcements when voltage is low.
uint32_t announcementInterval = defaultAnnouncementInterval
uint32_t alarmInterval = defaultAlarmInterval
uint32_t txHz = defaultFrequency
Initial frequency of the 'carrier wave' tones.
} settings
uint32_t uptime
elapsedMicros sinceUptime
Detailed Description
Implementation of user settings.
Definition in file settings.cpp.
Function Documentation
char* getAlarmHighBuffer ()
Returns a pointer to the alarm buffer template. Used to update the format.
Definition at line 116 of file settings.cpp.
Referenced by readEvalPrint().
{
    return settings.alarmHighFormat;
 }
char* getAlarmLowBuffer ()
Returns a pointer to the alarm buffer template. Used to update the format.
Definition at line 108 of file settings.cpp.
Referenced by readEvalPrint().
{
    return settings.alarmLowFormat;
 }
char* getAnnouncementBuffer ()
Returns a pointer to the announcement buffer template. Used to update the format.
Definition at line 100 of file settings.cpp.
Referenced by readEvalPrint().
{
    return settings.announcementFormat;
 }
const char* getAnnouncementFormatDefault ()
Returns the message format template BAT V MV ? V MV See txString() for a description of the format parameters such as V.
Definition at line 37 of file settings.cpp.
Referenced by readMessageFormat().
{
    return defaultAnnouncementFormat;
 }
const int32_t getMaximumVoltage ()
Get the maximum voltage the appliance is designed to accept. Returns 16000 mV.
Definition at line 27 of file settings.cpp.
Referenced by dispatchOnStack(), and readEvalPrint().
{
    return maximumVoltage;
 }
bool isTimeSet ()
Has the user set the time?
Note
The uptime is only updated when the time is set. This gives the user the opportunity to see the uptime before the first power failure if power is intermittent.
Definition at line 138 of file settings.cpp.
Referenced by printLog().
                  {
    return timeIsSet;
 }
void updateUptime ()
If 15 minutes have elapsed since last time, write to EEPROM.
Until the user sets the time, the uptime stays fixed at whatever value was stored in EEPROM. Once the user sets the time, the value starts updating to EEPROM every 15 minutes. So in the case of intermittent power, this will tell you the duration of the first interval. Which is not a bad thing to know.
Definition at line 144 of file settings.cpp.
References EEPROM_writeAnything(), and uptime.
Referenced by readEvalPrint().
                     {
    if (15 * 60 * 1000000 <= sinceUptime) {
       ++uptime;
       (void) EEPROM_writeAnything(0, uptime);
       sinceUptime = 0;
    }
 }
Variable Documentation
uint32_t alarmInterval = defaultAlarmInterval
Repeat the low-voltage alarm when the time in seconds is a multiple of this number.
Definition at line 85 of file settings.cpp.
uint32_t announcementInterval = defaultAnnouncementInterval
Repeat the announcement when the time in seconds is a multiple of this number.
Definition at line 81 of file settings.cpp.
int32_t highVoltageThreshold = highVoltageThresholdDefault
High-voltage alert threshold in millivolts. Note: the hardware has been tested briefly at 19.6V, but the design target is a 12V battery. The theoretical maximum input voltage is approximately 34V based on the voltage divider, the ADC maximum input voltage of 3.3V, and the reverse voltage protection diode, but that doesn't account for thermal stress.
The voltage divider values are 993 KOhm and 107.5 KOhm.
Definition at line 65 of file settings.cpp.
int32_t lowVoltageThreshold = lowVoltageThresholdDefault
Low-voltage alert threshold in millivolts. Note: if the low-voltage threshold is lower than the transmitter's minimum voltage, or lower than the microprcessor's minimum voltage, the alarm will not be transmitted.
Definition at line 55 of file settings.cpp.
uint32_t uptime
Number of 15-minute intervals since power on. The value gets written to EEPROM when it exceeds 2 (30 minutes) so that it is possible to see how long the previous uptime was.
Definition at line 94 of file settings.cpp.
Referenced by updateUptime().