Didah Morse Code PDA/Appliance: stack.h File Reference
stack.h File Reference
Fixed-sized stack for plain old data.
Classes
class Stack< T, N >
Fixed-sized stack for plain old data.
Functions
void popN (uint8_t n)
Pop the stack n times or until it is empty.
uint32_t stackDigitsToUnsigned ()
Stack Wrapper Functions
MorseToken s (size_t i)
Access the stack using an index where 0 is the top of the stack.
size_t symbolStackSize ()
void pushSymbolStack (MorseToken code)
void popSymbolStack (MorseToken)
void exchangeStack (MorseToken)
Swap s0 and s1.
void clearSymbolStack (MorseToken)
Discard all elements of the stack.
Detailed Description
Fixed-sized stack for plain old data.
No memory allocation or deallocation is performed.
Definition in file stack.h.
Function Documentation
void popSymbolStack (MorseToken)
Discard the top element of the stack unless the stack is empty in which case do nothing.
Definition at line 33 of file stack.cpp.
References Stack< T, N >::pop().
Referenced by askNext(), Stack< T, N >::clear(), and txAlphaNNN().
{
   tokenStack.pop();
 }
void pushSymbolStack (MorseToken code)
Push a symbol on to the symbol stack. If the stack is already full, simply overwrite the top of the stack.
Definition at line 27 of file stack.cpp.
References Stack< T, N >::push().
Referenced by askNext(), askNextAlfa(), askSum(), Stack< T, N >::clear(), dispatchOnStack(), getDigitByWeight(), push1RestoreAll(), and setup().
{
   tokenStack.push(code);
 }
MorseToken s (size_t i)
Access the stack using an index where 0 is the top of the stack.
Fetch element i of the stack. The top element is s(0). No error checking is done.
Definition at line 17 of file stack.cpp.
References symbolStackSize().
Referenced by askNext(), gradeSum(), matchScore(), playNote(), playSoundEffect(), setVolume(), stackDigitsToUnsigned(), txAlphabetSong(), txAlphaNNN(), txListSymbolStack(), txMetronome(), and txSymbolStackTop().
{
   MorseToken result(0);
   if (i < symbolStackSize()) {
     result = tokenStack[i];
   }
   return result;
 }
uint32_t stackDigitsToUnsigned ()
Interpret the digits on the stack as an unsigned 32-bit integer.
Note
There is no overflow check. 0 to 2147483647 should work.
Definition at line 58 of file stack.cpp.
References m2i(), popN(), s(), and symbolStackSize().
Referenced by Stack< T, N >::clear(), and dispatchOnStack().
{
    uint32_t n(0);
    uint32_t place(1);
    // Gobble up the digits on the stack, converting to a number.
    // Note, the cast is to insure that the range check can be
    // done in a single compare.
    while (symbolStackSize() && (uint8_t(s(0).toChar()) - '0' < 10)) {
       uint32_t d(s(0).m2i());
       n += place * d;
       place *= 10;
       popN(1);
    }
    return n;
 }
size_t symbolStackSize ()
Report the stack size. This function provides a little insulation so that we can change the implementation.
Definition at line 12 of file stack.cpp.
References Stack< T, N >::size().
Referenced by askNext(), Stack< T, N >::clear(), gradeSum(), matchScore(), playNote(), playSoundEffect(), s(), setVolume(), stackDigitsToUnsigned(), txAlphabetSong(), txAlphaNNN(), txListSymbolStack(), and txMetronome().
{
   return tokenStack.size();
 }