Didah Morse Code PDA/Appliance: teensy3_morse_bsp.cpp File Reference
teensy3_morse_bsp.cpp File Reference
Implementation of Teensy 3.0 board support package.
#include <climits>
#include "teensy3_morse_bsp.h"
#include "mk20dx128.h"
#include "cpu.h"
#include "libmorse.h"
#include "voltage_monitor.h"
Functions
char * identifyProcessor ()
Return a pointer to a static string that identifies the processor chip.
uint16_t touchMargin (60)
void calibrateTouch (uint8_t pin)
Establish a baseline for a touch sensor when no touch is present.
uint16_t getPinThreshold (uint8_t pin)
Return the pin capacitance in pF.
bool touchPoll (uint8_t pin)
size_t getDuty ()
void setDuty (uint8_t dutyCycle)
bool isEarphonePresent ()
void pollEarphonePresent ()
void beep (uint32_t frequency, uint32_t durationMicros)
Output a square wave on pin 10 at the given frequency for the given duration.
float getInternalTemperatureC ()
long readMillivolts ()
Return the most recent ADC measurement of the input voltage. Perform analog to digital conversion on the analogInput pin, callibrated to the protection diode and voltage divider on the interface/power board.
void sampleVoltage ()
Increment the voltage sampling and filtering.
void describeRTC ()
Report register settings related to the external clock crystal.
bool hasRTC ()
Sense whether or not a realtime clock crystal is present.
void initPorts ()
Initialize the input and output ports used by appliance or PDA hardware.
void pwmFrequency (int Hz)
Set the PWM frequency for the audio output pins.
void pwmWrite (int duty)
Generate a tone on the audio output pins.
void dWrite (int value)
Perform digital writes to all the output pins.
void redLED (int value)
Turn the red LED on (1) or off (0).
void greenLED (int value)
Turn the green LED on (1) or off (0).
uint16_t activityLight (0)
void toggleGreenLED ()
Change the state of the green LED.
void toggleRedLED ()
Change the state of the red LED.
uint32_t getRawVoltage ()
Get the raw analog input.
Variables
char cpuid [] = "012345678911234567892123456789"
size_t duty = duty50
bool earphonePresent = false
VoltageMonitor voltageMonitor
Detailed Description
Implementation of Teensy 3.0 board support package.
Definition in file teensy3_morse_bsp.cpp.
Function Documentation
void beep (uint32_t frequency, uint32_t durationMicros)
Output a square wave on pin 10 at the given frequency for the given duration.
Generate a tone using PWM.
Definition at line 179 of file teensy3_morse_bsp.cpp.
References pwmFrequency(), pwmWrite(), and redLED().
Referenced by blinkMorseDigit(), bmd096(), bmd104(), and txLiteral().
{
    pollEarphonePresent();
    pwmFrequency(frequency);
    pwmWrite(duty);
    redLED(1);
    delayMicroseconds(durationMicros);
    pwmWrite(0);
    redLED(0);
 }
void calibrateTouch (uint8_t pin)
Establish a baseline for a touch sensor when no touch is present.
Measure the noise floor for the given touch pin. A threshold is set 600pF above the maximum measured value.
Definition at line 135 of file teensy3_morse_bsp.cpp.
References pwmWrite().
Referenced by initPorts().
{
   touchBase[pin] = 0;
   for (int i(0); i < 10; ++i) {
     uint16_t pF20(touchRead(pin));
     pwmWrite(pF20);
     touchBase[pin] = touchBase[pin] < pF20 ? pF20 : touchBase[pin];
     delay(100);
   }
 }
void describeRTC ()
Report register settings related to the external clock crystal.
Turns out by the time user code runs, it's too late to change any of these clock registers.
From http://forum.pjrc.com/threads/724-32-768-KHz-crystal-and-battery-for-Teensy-3-0-RTC-questions?highlight=RTC_TPR The bit to use is RTC_SR_TIF, but you can't easily do this because the startup code checks that bit and tries to initialize the RTC. By the time your program is running, it's too late to discover what that bit was before the startup code ran.
There is a startup_early_hook() function you could implement to run your own code very early in the startup. Pretty much nothing is initialized at that point. The most viable solution would be to grab the value of RTC_SR and put it into a static variable. But this code runs before variables are initialized, so you'll have to use an attribute to put that variable into the .noinit section to prevent the later startup code from overwriting it. Then you could check that variable's RTC_SR_TIF bit once your program is running. Or if you don't need to do much, you could perhaps do everything you need in that extremely early startup code.... but that's quite difficult because so much stuff ordinary programming depends upon hasn't been initialized yet.
Definition at line 232 of file teensy3_morse_bsp.cpp.
Referenced by readEvalPrint().
                    {
   printLabelValueUnits("RTC_TSR ", RTC_TSR, " time in seconds");
   printLabelValueUnits("RTC_CR & RTC_CR_CLKO ",
                !!(RTC_CR & RTC_CR_CLKO), " 1=gated");
   printLabelValueUnits("RTC_CR & RTC_CR_OSCE ",
                !!(RTC_CR & RTC_CR_OSCE), " 1=enabled");
   printLabelValueUnits("RTC_SR & RTC_SR_TCE ",
                !!(RTC_SR & RTC_SR_TCE), " 1=enabled");
   printLabelValueUnits("RTC_SR & RTC_SR_TIF ",
                !!(RTC_SR & RTC_SR_TIF), " 1=invalid");
   printLabelValueUnits("RTC_SR & RTC_SR_TCE ",
                !!(RTC_SR & RTC_SR_TCE), " 1=prescale enabled");
   printLabelValueUnits("RTC_TPR ", RTC_TPR, " prescaler");
 }
float getInternalTemperatureC ()
Report the CPU temperature in Celsius units. Calibration was performed with a refrigerator, a heat gun, and a multimeter with a thermocouple.
Definition at line 193 of file teensy3_morse_bsp.cpp.
Referenced by printLog(), txInternalTemperatureC(), txInternalTemperatureF(), and txString().
{
    const double offset(343.8);
    const double gain(-0.02258);
    double reading(analogRead(temperatureSensor));
    return offset + gain * reading;
 }
uint16_t getPinThreshold (uint8_t pin)
Return the pin capacitance in pF.
Return the capacitance threshold in internal units of approximately pF/20 per count.
Definition at line 146 of file teensy3_morse_bsp.cpp.
Referenced by txTock().
{
   return 50 * (touchBase[pin] + touchMargin);
 }
bool hasRTC ()
Sense whether or not a realtime clock crystal is present.
Alas, all the flags I can find give no indication whether the RTC external clock crystal is or is not present. The RTC prescaler should increment approximately once every 31 microseconds, so we sample the prescaler, wait 33 microseconds, and sample again. If the value is unchanged, there is no RTC external crystal, but if the prescaler value has changed, then there is.
The flags I looked at were the following: !!(RTC_CR & RTC_CR_CLKO) !!(RTC_CR & RTC_CR_OSCE) !!(RTC_SR & RTC_SR_TCE) !!(RTC_SR & RTC_SR_TIF) !!(RTC_SR & RTC_SR_TCE)
Definition at line 260 of file teensy3_morse_bsp.cpp.
Referenced by readEvalPrint().
               {
   uint32_t prescaler(RTC_TPR);
   delayMicroseconds(33);
   return prescaler != RTC_TPR;
 }
bool touchPoll (uint8_t pin)
Poll the given capacitive sensor pin. Return true if the value is greater than the calibration threshold for the pin.
Definition at line 152 of file teensy3_morse_bsp.cpp.
References duty50.
Referenced by flushTouch(), getMorse(), getPressure(), txMetronome(), txString(), and txUnsigned().
{
   uint16_t pF20(touchRead(pin));
   return touchBase[pin] + touchMargin < pF20;
 }